### ISSUE TITLE
scoped does not work with SCSS

### ISSUE THREAD

**Issue by aibolit** [FranckFreiburger/vue3-sfc-loader#203]
**Describe the bug**

`<style scoped>` adds a suffix to all levels (parent/child) of selectors for scss
This causes the error `Could not compile style sass.Exception [Error]: Selector "[data-v-somehash]" can't have a suffix`

**To Reproduce**
have a scoped style with a parent/child selector such as

``` scss
.foo {
    &__bar {
         cursor: pointer; // any style
    }
}
```

Then run `compileString` from the npm library `sass` on the argument string to `addStyle`

it will break because the output style will be 

``` scss
.foo[data-v-somehash] {
    &__bar[data-v-somehash] {
         cursor: pointer; // any style
    }
}
```

**Expected behavior**
`scoped` causes the suffix to only be added to the most child level of the scss rules so that the styles can be compiled

**Versions**
 - Browser (name & version): any
 - vue3-sfc-loader: `0.9.5`
